######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 19 20:44:18 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
